Detail viewcontroller redesign - Redesigned DetailWeatherViewController, small redesign to HomeViewController, added new data to currentWeather model (wind)
dnikolic98/weatherApp pull request #2
Opened 2020-08-11 08:34 UTC by dnikolic98

HomeViewController
![HomeViewController](https://user-images.githubusercontent.com/42878987/89875832-0b6a3380-dbbe-11ea-8056-10040800b29d.png)

End of HomeViewController
![EndOfHomeViewController](https://user-images.githubusercontent.com/42878987/89875828-0ad19d00-dbbe-11ea-9103-6c733db5c94d.png)

DetailWeatherViewController
![DetailWeatherViewController](https://user-images.githubusercontent.com/42878987/89875822-0907d980-dbbe-11ea-84a4-d057b1d8726a.png)

2020-08-11 14:49 UTC, istaudacher requested changes

2020-08-11 14:49 UTC, istaudacher commented on weatherApp/Views/WeatherConditionDetailCollectionViewCell.swift
> +    func set(condition: String, value: String){
`) {`

2020-08-11 14:49 UTC, istaudacher commented on weatherApp/Features/WeatherDetails/UI/DetailWeatherViewController.swift
> +    private var weatherConditions: [(name: String, value: String)] = []
Why don't you create a struct instead of a tuple?

2020-08-11 14:49 UTC, istaudacher commented on weatherApp/Features/WeatherDetails/UI/DetailWeatherViewController.swift
> +    private func numOfConditions() -> Int {
`func` that have no argument and return value should be a computed property

2020-08-11 14:49 UTC, istaudacher commented on weatherApp/Features/WeatherDetails/UI/DetailWeatherViewController.swift
> +        tempLabel.text = String(String(format: LocalizedStrings.temperatureValueFormat, Int(forecast.temperature.celsius)).dropLast(2))
This is some magic to build a string :) Please reformat this to some meaningful way. Also, dropFirst without checking might throw an error, check the documentation.

2020-08-11 14:49 UTC, istaudacher commented on weatherApp/Features/WeatherDetails/UI/DetailWeatherViewController.swift
> +        let padding = CGFloat(20)
`let padding: CGFloat = 20`

2020-08-11 14:49 UTC, istaudacher commented on weatherApp/Features/WeatherDetails/UI/DetailWeatherViewController.swift
> +    private func setupCollectionViewHeight(){
`) {`

2020-08-11 14:49 UTC, istaudacher commented on weatherApp/Features/WeatherList/UI/HomeViewController.swift
> +    private let rowHeight = CGFloat(100.0)
`private let rowHeight: CGFloat = 100`

2020-08-11 14:49 UTC, istaudacher commented on weatherApp/Features/WeatherList/UI/HomeViewController.swift
> +    private func setupNavigationBar(){
styleNavigationBar

2020-08-12 08:57 UTC, labasbozidar requested changes

2020-08-12 08:57 UTC, labasbozidar commented on weatherApp/Features/WeatherDetails/UI/DetailWeatherViewController.swift
> +        let padding: CGFloat = 20
Extract this in constant because it is used in two places.

2020-08-12 09:05 UTC, labasbozidar approved these changes

2020-08-12 11:04 UTC, istaudacher approved these changes

2020-08-12 11:33 UTC, merged